# Generated by Django 4.1.3 on 2023-04-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0004_alter_project_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.issue'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.project'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('0', 'FAIBLE'), ('1', 'MOYENNE'), ('2', 'ÉLEVÉE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('0', 'À FAIRE'), ('1', 'EN COURS'), ('2', 'TERMINÉ')], max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('0', 'BUG'), ('1', 'AMÉLIORATION'), ('2', 'TÂCHE')], max_length=1),
        ),
    ]
