# Generated by Django 4.1.3 on 2023-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_comment_author_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('0', 'BACK-END'), ('1', 'FRONT-END'), ('2', 'iOS'), ('3', 'ANDROID')], max_length=1),
        ),
    ]
